apiVersion: v1
kind: ConfigMap
metadata:
  name: sc4snmp-config
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yaml: |-
    celery:
      broker:
        type: "rabbitmq"
    # Sample Configuration file
    ipv4: True
    ipv6: False
    poller:
{{- if (.Values.files.scheduler.config.poller).usernames }}
      usernames:
{{ .Values.files.scheduler.config.poller.usernames | indent 8 -}}
{{ end }}
{{- if (.Values.files.scheduler.config.poller).profiles }}
      profiles:
{{ .Values.files.scheduler.config.poller.profiles | indent 8 -}}
{{ end }}
{{- if (.Values.files.scheduler.config.poller).communities }}
      communities:
{{ .Values.files.scheduler.config.poller.communities | indent 8 }}
{{ else }}
      communities:
        public:
          communityIndex:
          contextEngineId:
          contextName:
          tag:
          securityName:
{{- end -}}
{{- if (.Values.files.scheduler.config.poller).additionalMetricField }}
      additionalMetricField:
{{ .Values.files.scheduler.config.additionalMetricField | indent 8 }}
{{- end -}}