{{- if .Values.sim.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-connect-for-snmp.name" . }}-sim
  namespace: {{ .Release.Namespace | quote }}
data:
  otel-collector-config.yaml: |
    receivers:
      splunk_hec/metrics:
        endpoint: 0.0.0.0:8882
      splunk_hec/logs:
        endpoint: 0.0.0.0:8883
    exporters:
      logging:
        loglevel: DEBUG
      signalfx:
        access_token: $signalfxToken
        realm: $signalfxRealm
    service:
      telemetry:
      pipelines:
        metrics:
          receivers: [splunk_hec/metrics]
          exporters: [signalfx]
        logs:
          receivers: [splunk_hec/logs]
          exporters: [signalfx, logging]
{{- end }}
