{{- if ( include "splunk-connect-for-snmp.sim.autoscaling" . ) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "splunk-connect-for-snmp.sim.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.sim.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "splunk-connect-for-snmp.sim.fullname" . }}
  minReplicas: {{ .Values.sim.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.sim.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.sim.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sim.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
