{{- if (include "splunk-connect-for-snmp.sim.serviceAccountCreate" .) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-connect-for-snmp.sim.serviceAccountName" . }}
  labels:
    {{- include "splunk-connect-for-snmp.sim.labels" . | nindent 4 }}
  {{- with (include "splunk-connect-for-snmp.sim.serviceAccountAnnotations" .) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
