# Default values for splunk-connect-for-snmp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

################################################################################
# SC4SNMP image settings
################################################################################

image:
  # The registry and name of the SC4SNMP image to pull
  repository: ghcr.io/splunk/splunk-connect-for-snmp/container
  # The policy that specifies when the user wants the SC4SNMP images to be pulled
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Secrets to attach to the respective serviceaccount to pull docker images
imagePullSecrets: []


################################################################################
# Splunk Data-to-Everything Platform configuration
################################################################################

splunk:
  # Enables sending data to Splunk
  enabled: true
  # the protocol of the HEC endpoint: https or http
  protocol: ""
  # the port of the HEC endpoint
  port: "8088"
  # IP address or a domain name of a Splunk instance to send data to.
  host: ""
  # the protocol, host and port given here makes up to a HEC endpoint
  # according to the pattern: {{protocol}}://{{host}}:{{port}}/services/collector
  # for ex. https://splunk-endpoint:8088/services/collector

  # Required for Splunk Enterprise/Cloud (if `enabled` is set to true). Splunk
  # HTTP Event Collector token.
  token: 00000000-0000-0000-0000-000000000000
  # Whether to skip checking the certificate of the HEC endpoint when sending
  # data over HTTPS.
  insecureSSL: "true"

################################################################################
# Splunk Observability configuration
################################################################################

sim:
  # Enables sending data to Splunk Observability/SignalFx.
  enabled: false

  # Splunk Observability realm to send telemetry data to.
  signalfxToken: ""
  # Required for Splunk Observability (if `realm` is specified). Splunk
  # Observability org access token.
  signalfxRealm: ""

  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  autoscaling:
    enabled: false

  ingress:
    enabled: false

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 200m
    #   memory: 256Mi


  service:
    annotations: {}

  secret:
    # Option for creating a new secret or using an existing one.
    # When secret.create=true, a new kubernetes secret will be created by the helm chart that will contain the
    # values from sim.signalfxToken and sim.signalfxRealm.
    # When secret.create=false, the user must set secret.name to a name of a k8s secret the user created.
    create: true
    name: ""

################################################################################
# SC4SNMP image settings
################################################################################

inventory:
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 200m
    #   memory: 256Mi

scheduler:
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  resources: {}
#     limits:
#       cpu: 800m
#       memory: 512Mi
#     requests:
#       cpu: 500m
#       memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  podAntiAffinity: soft

worker:
  taskTimeout: 2400
  walkRetryMaxInterval: 600
  ignoreNotIncreasingOid: []
  poller:
    replicaCount: 2
    concurrency: 4
    prefetch: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 250m
  trap:
    replicaCount: 2
    concurrency: 4
    prefetch: 30
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 250m
  sender:
    replicaCount: 1
    concurrency: 4
    prefetch: 30
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 250m
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  resources:
     limits:
       cpu: 500m
       memory: 5128Mi
     requests:
       cpu: 300m
       memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  podAntiAffinity: soft

poller:
  usernameSecrets: []


traps:
  replicaCount: 2
  usernameSecrets: []
  securityEngineId:
    - "80003a8c04"

  communities: {}
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  service:
    annotations: {}
    usemetallb: true
    metallbsharingkey: "splunk-connect"
    type: LoadBalancer
    port: 162

  ingress:
    enabled: false
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 1Gi
    # requests:
    #   cpu: 200m
    #   memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  

  podAntiAffinity: soft

#############################################################################
### Please do not modify below values, unless you know what you're doing! ###
#############################################################################
mongodb:
  architecture: "standalone"
  ## @section Global parameters
  ## Global Docker image parameters
  ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
  ## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

  ## @section Common parameters
  ##

  ## @param clusterDomain Default Kubernetes cluster domain
  ##
  clusterDomain: cluster.local

  ##
  auth:
    ## @param auth.enabled Enable authentication
    ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
    ##
    enabled: false

  ## MongoDB&reg; containers' resource requests and limits.
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## @param resources.limits The resources limits for MongoDB&reg; containers
  ## @param resources.requests The requested resources for MongoDB&reg; containers
  ##
  rbac:
    create: true
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 768Mi
    # requests:
    #   cpu: 250m
    #   memory: 512Mi

  ## @section Volume Permissions parameters

  ## @section Metrics parameters

  metrics:
    ## @param metrics.enabled Enable using a sidecar Prometheus exporter
    ##
    enabled: true
    containerPort: 9216
    ## Prometheus Exporter service configuration
    ##
    service:
      ## @param metrics.service.annotations [object] Annotations for Prometheus Exporter pods. Evaluated as a template.
      ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
      ##
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
redis:
  architecture: standalone
  auth:
    enabled: false
commonAnnotations: {}