{{- if (include "splunk-connect-for-snmp.scheduler.serviceAccountCreate" .) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-connect-for-snmp.scheduler.serviceAccountName" . }}
  labels:
    {{- include "splunk-connect-for-snmp.scheduler.labels" . | nindent 4 }}
  {{- with (include "splunk-connect-for-snmp.scheduler.serviceAccountAnnotations" .) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
