{{- if ( include "splunk-connect-for-snmp.sim.autoscaling" . ) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "splunk-connect-for-snmp.traps.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.traps.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "splunk-connect-for-snmp.traps.fullname" . }}
  minReplicas: {{ .Values.traps.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.traps.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.traps.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.traps.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
