apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: mher/flower
          env:
            - name: CELERY_BROKER_URL
              value: redis://snmp-redis-headless:6379/0
          ports:
            - containerPort: 5555