apiVersion: v1
kind: Service
metadata:
  name: flower-svc
  namespace: default

spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
  type: LoadBalancer
  externalIPs:
    - 10.202.16.140